#ifndef FDSI_DEFINITIONS_HH
#define FDSI_DEFINITIONS_HH

#define FD_MAX_CRATES 4
#define FD_MAX_SLOTS_PER_CRATE 13
#define FD_MAX_CHANNELS_PER_BOARD 16
#define MAX_HITS 100
#define MAX_GAMMAS 100
#define MAX_CLOVERS 24
#define MAX_BETACUTS 30

#endif
